# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\x12\x08\x63ustomer\"1\n\x08\x43ustomer\x12\x14\n\x0c\x63ustomerName\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\'\n\x0f\x43ustomerRequest\x12\x14\n\x0c\x63ustomerName\x18\x01 \x01(\t2O\n\x0f\x43ustomerService\x12<\n\x0bGetCustomer\x12\x19.customer.CustomerRequest\x1a\x12.customer.Customerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMER']._serialized_start=28
  _globals['_CUSTOMER']._serialized_end=77
  _globals['_CUSTOMERREQUEST']._serialized_start=79
  _globals['_CUSTOMERREQUEST']._serialized_end=118
  _globals['_CUSTOMERSERVICE']._serialized_start=120
  _globals['_CUSTOMERSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
